/*!
 * teacher-agent-sandbox · 工作流提示词模板 (workflow-prompts.js)
 * ------------------------------------------------------------------
 * 为 LangGraph 工作流的每个阶段节点定义结构化提示词模板。
 * 采用 LangChain PromptTemplate 风格：{变量名} 占位，运行时填充。
 * 每个模板聚焦一个阶段职责，避免单次提示词过载导致输出缩水。
 */
(function (global) {
  'use strict';

  var Prompts = {

    /* ============ 阶段1：高级意图识别（多产物路由） ============ */
    classify: [
      '你是教学智能体的高级意图识别器。分析教师的备课请求，解析出全部产物需求，输出严格 JSON。',
      '```json',
      '{',
      '  "products": ["子工作流ID数组，如 lesson-plan/ppt/animation/exercise/student-analysis/explainer/worksheet/assessment/unit-design/differentiation/grading/error-analysis/ppt-page/report-page"],',
      '  "quantities": { "ppt": 15, "exercise": 10, "animation": 1 }(各产物的数量要求，未提及可省略),',
      '  "studentTags": ["学情标签数组，如 基础中等/基础薄弱/计算易错/尖子生"],',
      '  "subject": "学科(从请求或上下文推断)",',
      '  "grade": "年级(从请求或上下文推断)",',
      '  "topic": "课题(从请求中提取，如《函数的单调性》)",',
      '  "needsResearch": true/false(是否需要联网搜课标/真题),',
      '  "needsStudentData": true/false(是否需要读取学情记忆),',
      '  "confidence": 0-100(信息完整度置信度),',
      '  "missingInfo": ["缺失的关键信息字段，如 subject/grade/topic/products"],',
      '  "priority": "high/mid/low"',
      '}',
      '```',
      '识别规则：',
      '- products 必须列出教师要求的所有产物；未指定产物类型时给默认 lesson-plan',
      '- 从"教案/教学设计"识别 lesson-plan，从"PPT/课件"识别 ppt，从"动画/演示/动态图"识别 animation',
      '- 从"习题/试卷/题目"识别 exercise，从"学情/分析报告"识别 student-analysis',
      '- 从"精讲/重难点讲解/任务拆解"识别 explainer，从"学案"识别 worksheet',
      '- 从"量规/评价表"识别 assessment，从"大单元"识别 unit-design，从"分层"识别 differentiation',
      '- 从"批改/阅卷"识别 grading，从"易错/重点难点/考点分析"识别 error-analysis',
      '- 从"HTML演示/网页PPT/slide cards"识别 ppt-page，从"报告/研究报告/文档页面"识别 report-page',
      '- missingInfo 仅列影响执行的关键字段（subject/grade/topic/products），可从上下文推断的不要列入',
      '只输出 JSON，无解释。',
      '',
      '教师请求：{userInput}',
      '上下文：学科={subject}，年级={grade}，课题={topic}',
    ].join('\n'),

    /* ============ 阶段1.5：信息补全（澄清追问） ============ */
    disambiguate: [
      '你是教学智能体的需求澄清专家。教师请求缺少关键信息，请生成定向追问问题（选择题形式），输出严格 JSON：',
      '```json',
      '{',
      '  "reason": "为什么需要追问（简要说明缺失信息对备课的影响）",',
      '  "questions": [',
      '    {',
      '      "q": "问题文本（如：请问课题对应的年级是？）",',
      '      "options": ["选项A","选项B","选项C","选项D","其他"],',
      '      "multi": false',
      '    }',
      '  ]',
      '}',
      '```',
      '要求：',
      '- 只针对 missingInfo 中的关键字段提问，1-3 个问题即可',
      '- 每个问题 2-5 个具体选项，最后一个固定为"其他"',
      '- 能合理推断的字段不要问，不要为了问而问',
      '',
      '教师原始请求：{userInput}',
      '缺失信息：{missingInfo}',
    ].join('\n'),

    /* ============ 阶段2：资料搜集（课标+真题） ============ */
    research: [
      '你是教研资料搜集专家。基于课题，提炼需要搜索的关键信息，输出严格 JSON：',
      '```json',
      '{',
      '  "searchQueries": [',
      '    "搜索关键词1（课标要求方向）",',
      '    "搜索关键词2（高考真题/考法方向）"',
      '  ],',
      '  "focusAreas": [',
      '    "需要关注的课标要点1",',
      '    "需要关注的高考考法1"',
      '  ]',
      '}',
      '```',
      '要求：',
      '- searchQueries 给出2-3个精准搜索词，覆盖课标和高考两个维度',
      '- focusAreas 列出从搜索结果中需要提取的关键信息方向',
      '- 只输出 JSON',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '技能类型：{skillName}',
    ].join('\n'),

    /* ============ 阶段3：学情分析 ============ */
    analyze: [
      '你是学情分析专家。基于记忆系统中的学生数据，生成针对本课题的学情分析摘要。',
      '输出 Markdown 格式，包含：',
      '1. **已有基础**：学生在本课题相关的已有知识基础',
      '2. **常见困难**：学生可能遇到的理解困难和易错点',
      '3. **差异化需求**：不同层次学生的需求差异',
      '4. **教学建议**：基于学情的教学调整建议',
      '',
      '记忆中的学情数据：',
      '{studentMemory}',
      '',
      '课题：{topic}',
      '学科：{subject}',
      '若无学情数据，基于该年级该学科的常见学情给出通用分析。',
    ].join('\n'),

    /* ============ 阶段4：内容规划（详细大纲） ============ */
    plan: [
      '你是资深教研专家。基于课标要求、高考考法和学情分析，为本课题制定详细的内容生成大纲。',
      '输出严格 JSON：',
      '```json',
      '{',
      '  "title": "文档标题",',
      '  "structure": [',
      '    {',
      '      "section": "章节名称",',
      '      "requirements": "该章节的具体内容要求（写明要包含哪些元素）",',
      '      "minChars": 300(该章节最低字数)',
      '      "keyPoints": ["要点1","要点2"]',
      '    }',
      '  ],',
      '  "totalEstChars": 3500(预估总字数),',
      '  "qualityNotes": "质量注意事项"',
      '}',
      '```',
      '要求：',
      '- 大纲必须覆盖该技能类型的所有必备章节',
      '- 每个章节的 requirements 要具体到"写什么内容、含哪些元素"',
      '- keyPoints 列出该章节必须涵盖的知识点或要素',
      '- 只输出 JSON',
      '',
      '技能类型：{skillName}',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '课标与考法资料：',
      '{researchData}',
      '',
      '学情分析：',
      '{studentAnalysis}',
    ].join('\n'),

    /* ============ 阶段5：内容生成 ============ */
    generate_lesson_plan: [
      '你是高中名师。基于大纲，生成一份完整、详尽、可直接使用的教案。',
      '',
      '【强制要求】',
      '1. 正文不少于 3000 字，宁可长不可空',
      '2. 必须包含以下全部章节：',
      '   - 课标依据与教材分析',
      '   - 学情分析（结合下方学情数据）',
      '   - 教学目标（核心素养四维度，用可观察可测量的行为动词）',
      '   - 教学重点、教学难点（各附突破策略）',
      '   - 教学过程（≥5个环节：情境导入/新知探究/例题精讲/变式训练/课堂小结）',
      '     每个环节必须写清：【教师活动】含具体提问话术原话、【学生活动】含预设回答、【设计意图】、【时间分配】',
      '   - 例题与变式（完整题干+逐行规范解答，数学公式用 LaTeX）',
      '   - 分层作业（基础/提升/拓展三层，给出具体题目）',
      '   - 板书设计（结构化呈现）',
      '   - 教学反思预设',
      '3. 禁止空泛表述：不写"此处讲解""举例说明""略"等，所有内容必须具体可操作',
      '4. 数学/物理/化学公式用 LaTeX 语法（$...$ 行内，$$...$$ 块级）',
      '5. 输出纯 Markdown 格式',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '课标与考法资料：',
      '{researchData}',
      '',
      '学情分析：',
      '{studentAnalysis}',
    ].join('\n'),

    generate_ppt: [
      '你是课件设计专家。基于大纲，生成结构化的 PPT 课件内容。',
      '输出严格 JSON（幻灯片数组）：',
      '```json',
      '[',
      '  {',
      '    "type": "title",',
      '    "title": "封面标题",',
      '    "subtitle": "副标题（学科+年级+课题）"',
      '  },',
      '  {',
      '    "type": "content",',
      '    "title": "页面标题",',
      '    "bullets": ["具体知识内容1","具体知识内容2","具体知识内容3"]',
      '  },',
      '  {',
      '    "type": "example",',
      '    "title": "例题标题",',
      '    "bullets": ["完整题干","解答步骤1","解答步骤2","最终答案"]',
      '  }',
      ']',
      '```',
      '',
      '【强制要求】',
      '1. 至少 12 页幻灯片',
      '2. 页面结构：封面/学习目标/目录/6-8页知识讲授/例题页(含完整解答)/课堂练习页/小结页/作业页',
      '3. 每页 bullets 写具体知识内容（定义、性质、解题步骤的原话），禁止"讲解XX知识点"这类占位表述',
      '4. 例题页给出完整题目与分步解答',
      '5. 只输出 JSON 数组',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '课标与考法资料：',
      '{researchData}',
    ].join('\n'),

    generate_worksheet: [
      '你是学案设计专家。基于大纲，生成一份完整的五段式学案。',
      '',
      '【强制要求】',
      '1. 正文不少于 2000 字',
      '2. 必须包含以下全部部分：',
      '   - 学习目标（可检测的行为动词）',
      '   - 课前预习（含具体填空题和思考题，附引导材料）',
      '   - 课堂探究问题链（3-4个由浅入深的递进问题，每问附教师引导语）',
      '   - 当堂检测（5-8题，覆盖核心知识点，附完整答案与逐题解析）',
      '   - 课后巩固（基础题+提升题分层）',
      '3. 所有题目给出具体题干，禁止占位',
      '4. 数学公式用 LaTeX',
      '5. 输出纯 Markdown 格式',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '学情分析：',
      '{studentAnalysis}',
    ].join('\n'),

    generate_exam: [
      '你是命题专家。基于大纲和高考考法，生成一份标准化考试试卷。',
      '',
      '【强制要求】',
      '1. 试卷结构遵循高考标准（选择12题+填空4题+解答6题，满分150分，时间120分钟，或按学科调整）',
      '2. 每题标注分值',
      '3. 题目难度梯度：易30%/中50%/难20%',
      '4. 数学/物理/化学公式用 LaTeX',
      '5. 每题解析含解题思路、关键步骤与易错点（放在试卷末尾，用分页符分隔）',
      '6. 题干完整、选项规范，禁止"略"等省略',
      '7. 输出纯 Markdown 格式',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '高考考法资料：',
      '{researchData}',
    ].join('\n'),

    generate_assessment: [
      '你是评价专家。基于课题，设计多维度评价量规。',
      '',
      '【强制要求】',
      '1. 至少 4 个评价维度',
      '2. 每维度四等级（优秀/良好/合格/待改进）的具体行为描述',
      '3. 各维度权重之和为 100%',
      '4. 行为描述须具体可观察，如"能够在3分钟内准确写出..."',
      '5. 输出 Markdown 表格格式',
      '',
      '课题：{topic}',
      '学科：{subject}',
      '',
      '内容大纲：',
      '{outline}',
    ].join('\n'),

    generate_unit_design: [
      '你是大单元设计专家。基于课标大概念理念，设计完整的大单元教学规划。',
      '',
      '【强制要求】',
      '1. 正文不少于 2500 字',
      '2. 必须包含：单元大概念与基本问题、单元学习目标(对标课标)、核心评估任务(表现性任务+量规)、学习活动序列(WHERETO)、课时安排表、单元反思',
      '3. 输出纯 Markdown 格式',
      '',
      '单元主题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '课标资料：',
      '{researchData}',
    ].join('\n'),

    generate_differentiation: [
      '你是分层教学设计专家。基于学情，设计差异化教学路径。',
      '',
      '【强制要求】',
      '1. 正文不少于 2000 字',
      '2. 必须包含：班级学情画像、A层(基础巩固)/B层(能力提升)/C层(挑战拓展)各自的目标/任务/作业、课堂并行活动安排、辅导与评价策略',
      '3. 每层的任务和作业要给出具体题目或活动',
      '4. 输出纯 Markdown 格式',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '学情分析：',
      '{studentAnalysis}',
    ].join('\n'),

    generate_explainer: [
      '你是教学精讲专家。基于课题，生成「任务拆解与重难点精讲」文档。',
      '',
      '【输出约定】本任务输出 Markdown 文本。若你的接口要求输出 JSON，请输出 {"content":"<完整Markdown>"}。',
      '',
      '【强制要求】',
      '1. 正文不少于 1500 字',
      '2. 必须包含：',
      '   - 学习任务目标（可检测的行为动词）',
      '   - 前置知识诊断（学生需具备的已有知识及自查题）',
      '   - 任务链拆解（≥3个递进任务，每个任务含【指令】【示范】【评价点】）',
      '   - 重难点精讲（逐字稿级别，含推导过程、易错点警示、典型例题完整解答）',
      '   - 检测与反馈（2-3个检测题+反馈标准）',
      '3. 数学/物理/化学公式用 LaTeX',
      '4. 禁止占位表述',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '课标与考法资料：',
      '{researchData}',
      '',
      '学情分析：',
      '{studentAnalysis}',
    ].join('\n'),

    generate_animation: [
      '你是教学可视化专家。基于课题，设计一个可直接在课堂上演示的互动教学动画，输出严格 JSON 动画脚本。',
      '```json',
      '{',
      '  "title": "动画标题（含课题）",',
      '  "autoPlay": true,',
      '  "scenes": [',
      '    {',
      '      "title": "场景1：概念引入",',
      '      "svg": "<svg viewBox=\"0 0 800 450\" xmlns=\"http://www.w3.org/2000/svg\">...</svg>（自包含SVG，画面元素齐全，文字用中文，禁止引用外部图片）",',
      '      "narration": "讲解文本（教学口吻，说明本场景要传达的知识点）",',
      '      "interaction": "auto/click/hover/step（本场景的交互方式）",',
      '      "note": "教学要点与使用提示"',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '【强制要求】',
      '1. 至少 3 个场景，形成「引入→探究→结论/应用」的教学逻辑链',
      '2. 每个场景的 svg 必须是完整自包含的 SVG XML（可含 <g>/<rect>/<circle>/<line>/<text>/<path>/<animate>/<animateTransform> 等元素），',
      '   必须能把抽象知识可视化（如函数动态变化、运动过程、实验流程、数量关系对比）',
      '3. narration 用教师讲解口吻写清楚本场景讲什么、怎么讲',
      '4. interaction 说明交互方式：auto 自动播放 / click 点击触发 / hover 悬停展示 / step 分步演示',
      '5. 禁止占位：svg 中不得出现 "此处放图" 等占位文字，文字内容必须完整',
      '6. 只输出 JSON',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '重难点（动画需可视化突破）：',
      '{keyPoints}',
    ].join('\n'),

    generate_student_analysis: [
      '你是学情分析专家。基于班级学情数据和学情标签，生成一份可指导教学的学情分析报告。',
      '',
      '【输出约定】本任务输出 Markdown 文本。若你的接口要求输出 JSON，请输出 {"content":"<完整Markdown>"}。',
      '',
      '【强制要求】',
      '1. 正文不少于 800 字',
      '2. 必须包含：',
      '   - 班级整体掌握情况（结合数据）',
      '   - 高频易错点预判（结合考情数据）',
      '   - 分层教学策略（基础层/提升层/拓展层各自的目标与任务建议）',
      '   - 学困生辅导方案（具体到措施）',
      '   - 优生拓展方向（具体到资源类型）',
      '3. 必须逐条回应下方学情标签，说明对应教学调整',
      '4. 建议必须落地可操作，禁止空话',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '班级学情数据：',
      '{studentData}',
      '',
      '学情标签：',
      '{studentTags}',
    ].join('\n'),

    generate_grading: [
      '你是资深阅卷专家。按照题目批改技能规范，对学生作业或试卷进行逐题批改，生成完整的批改报告。',
      '',
      '【输出约定】本任务输出 Markdown 文本。若你的接口要求输出 JSON，请输出 {"content":"<完整Markdown>"}。',
      '',
      '【强制要求】',
      '1. 正文不少于 1500 字',
      '2. 必须包含以下全部部分：',
      '   - 批改信息（学科年级、题目类型与数量、总分与分值分配）',
      '   - 评分标准（客观题比对答案，主观题按得分点，作文分维度）',
      '   - 逐题批改详情（题号、满分、得分、对错标注、扣分原因），错误标注分类：【知识错误】【方法错误】【计算错误】【格式错误】【审题错误】',
      '   - 汇总评分（各题得分、总分、得分率）',
      '   - 错误统计（按错误类型分类统计）',
      '   - 总体评价（成绩等级、整体表现）',
      '   - 主要问题（按严重程度排序）',
      '   - 改进建议（针对性强、可操作）',
      '   - 鼓励性评语',
      '3. 每题批改必须标注具体得分与扣分原因，禁止只给总分',
      '4. 数学/物理/化学公式用 LaTeX',
      '5. 输出纯 Markdown 格式',
      '',
      '课题/试卷：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '课标与考法资料：',
      '{researchData}',
    ].join('\n'),

    generate_error_analysis: [
      '你是学科教研专家。按照重点及易错点分析技能规范，对指定知识范围进行系统化的重点提炼与易错点分析，生成结构化分析报告。',
      '',
      '【输出约定】本任务输出 Markdown 文本。若你的接口要求输出 JSON，请输出 {"content":"<完整Markdown>"}。',
      '',
      '【强制要求】',
      '1. 正文不少于 2000 字',
      '2. 必须包含以下全部部分：',
      '   - 分析概述（学科/年级/知识范围/分析目的）',
      '   - 知识结构图（本部分知识的整体结构，表格或文字描述）',
      '   - 重点知识分析（3-8个重点，每个含：重要性说明、课标要求、考查方式、掌握标准）',
      '   - 易错点分析（5-15个易错点，每个含六要素：错误表现→错因分析→正确理解→典型错例→纠错策略→变式训练）',
      '   - 错因分类汇总（按概念混淆型/审题不清型/计算失误型/思维定式型/知识遗忘型/表达不规范型分类）',
      '   - 教学建议（教学优先级排序+教学策略+复习策略）',
      '3. 每个易错点必须包含完整六要素，禁止缺项',
      '4. 错例必须给出具体题目和错误解答，不能笼统描述',
      '5. 数学/物理/化学公式用 LaTeX',
      '6. 输出纯 Markdown 格式',
      '',
      '知识范围：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '课标与考法资料：',
      '{researchData}',
    ].join('\n'),

    generate_ppt_page: [
      '你是课件设计专家。基于课题内容，生成结构化的 PPT 课件内容，输出严格 JSON（幻灯片数组），系统将通过 gen_ppt 生成 .pptx 文件。',
      '```json',
      '[',
      '  {',
      '    "type": "title",',
      '    "title": "封面标题",',
      '    "subtitle": "副标题（学科+年级+课题）"',
      '  },',
      '  {',
      '    "type": "content",',
      '    "title": "页面标题",',
      '    "bullets": ["具体知识内容1","具体知识内容2","具体知识内容3"]',
      '  },',
      '  {',
      '    "type": "example",',
      '    "title": "例题标题",',
      '    "bullets": ["完整题干","解答步骤1","解答步骤2","最终答案"]',
      '  }',
      ']',
      '```',
      '',
      '【强制要求】',
      '1. 至少 12 页幻灯片',
      '2. 页面结构：封面/学习目标/目录/6-8页知识讲授/例题页(含完整解答)/课堂练习页/小结页/作业页',
      '3. 每页 bullets 写具体知识内容（定义、性质、解题步骤的原话），禁止"讲解XX知识点"这类占位表述',
      '4. 例题页给出完整题目与分步解答',
      '5. 每页文字不超过6行，每行不超过20字，内容精炼充实',
      '6. 只输出 JSON 数组',
      '',
      '课题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '课标与考法资料：',
      '{researchData}',
    ].join('\n'),

    generate_report_page: [
      '你是报告页面设计专家。基于课题内容，生成一份源支持的可编辑静态 HTML 报告页面。',
      '',
      '【输出约定】本任务输出完整的 HTML 文本。若你的接口要求输出 JSON，请输出 {"content":"<完整HTML>"}。',
      '',
      '【强制要求】',
      '1. 输出完整的自包含 HTML 文件（首行必须是 <!-- Generated by Trae Work -->）',
      '2. 页面结构使用文档块组件：doc-block、doc-callout、doc-metrics、doc-chart、doc-table、doc-diagram、doc-note、doc-sources',
      '3. 页面内容须包含：',
      '   - 清晰的叙事主线（非简单堆砌组件）',
      '   - 侧边目录（由文档标题自动生成）',
      '   - 至少 3 个文档块（text/callout/metric/table/chart 等按需选用）',
      '   - 来源标注（doc-sources）',
      '4. 排版：Notion 风格的文档阅读体验，calm typography',
      '5. 如有数据图表，使用 ECharts 渲染（内联 JSON 数据 + doc-chart 容器）',
      '6. 页面文件应可直接用浏览器打开，所有样式内联或通过 doc.css 引入',
      '7. 禁止占位文本和示例内容',
      '',
      '报告主题：{topic}',
      '学科：{subject}，年级：{grade}',
      '',
      '内容大纲：',
      '{outline}',
      '',
      '课标与考法资料：',
      '{researchData}',
    ].join('\n'),

    /* ============ 阶段6：内容精炼（基于验证反馈修改） ============ */
    refine: [
      '你是教学内容的审校专家。以下内容未通过质量验证，请根据验证反馈进行修改完善。',
      '',
      '【修改原则】',
      '1. 只修改有问题的部分，保留已达标的内容',
      '2. 针对每个问题逐条修复',
      '3. 扩充不足的内容，补充缺失的章节',
      '4. 将占位表述替换为具体内容',
      '5. 输出完整的修改后内容（纯 Markdown），不要只输出修改片段',
      '',
      '课题：{topic}',
      '学科：{subject}',
      '',
      '=== 原始内容 ===',
      '{draftContent}',
      '',
      '=== 验证反馈 ===',
      '{validationFeedback}',
      '',
      '请输出修改后的完整内容。',
    ].join('\n'),

    /* ============ 阶段7：最终总结 ============ */
    finalize: [
      '你是智能体助手。基于工作流的执行结果，生成给教师的最终总结回答。',
      '要求：',
      '1. 用 Markdown 格式',
      '2. 列出生成的文件名与内容亮点',
      '3. 给出使用建议',
      '4. 不超过 300 字',
      '5. 不要重复文档全文（文档已通过工具生成可下载文件）',
      '',
      '生成的产物：',
      '{artifacts}',
      '',
      '质量评分：{qualityScore}/100',
      '',
      '课题：{topic}',
    ].join('\n'),

    /* ============ 阶段7.5：备课资源包总览（多产物统一输出） ============ */
    finalize_bundle: [
      '你是智能体助手。多子工作流并行已完成，生成给教师的备课资源包总览，输出严格 JSON：',
      '```json',
      '{',
      '  "summary": "资源包总览（Markdown，≤350字：说明本次生成的产物清单、内容亮点、使用建议、失败提示，不重复文档全文）",',
      '  "files": ["文件名1", "文件名2"],',
      '  "scores": { "lesson-plan": 85, "ppt": 90 }',
      '}',
      '```',
      '要求：',
      '- summary 用 Markdown，先列产物清单（文件名+类型），再给亮点与使用建议',
      '- 若有子任务失败，在 summary 末尾说明失败项与原因',
      '- 只输出 JSON',
      '',
      '课题：{topic}',
      '',
      '产物清单：',
      '{artifacts}',
      '',
      '质量评分（各子工作流）：',
      '{qualityScores}',
      '',
      '失败项：',
      '{failed}',
    ].join('\n'),
  };

  /**
   * 填充模板变量
   * @param {string} template - 模板字符串（含 {var} 占位符）
   * @param {object} vars - 变量键值对
   * @returns {string} 填充后的字符串
   */
  function fill(template, vars) {
    vars = vars || {};
    return String(template).replace(/\{(\w+)\}/g, function (match, key) {
      var val = vars[key];
      if (val === undefined || val === null) return '';
      if (typeof val === 'object') return JSON.stringify(val, null, 2);
      return String(val);
    });
  }

  /**
   * 根据技能ID获取对应的生成提示词
   * @param {string} skillId
   * @returns {string} 提示词模板
   */
  function getGeneratePrompt(skillId) {
    var map = {
      'lesson-plan': Prompts.generate_lesson_plan,
      'ppt-generator': Prompts.generate_ppt,
      'ppt': Prompts.generate_ppt,
      'worksheet': Prompts.generate_worksheet,
      'exam-generator': Prompts.generate_exam,
      'exercise': Prompts.generate_exam,
      'assessment': Prompts.generate_assessment,
      'unit-design': Prompts.generate_unit_design,
      'differentiation': Prompts.generate_differentiation,
      'explainer': Prompts.generate_explainer,
      'animation': Prompts.generate_animation,
      'student-analysis': Prompts.generate_student_analysis,
      // 新增技能提示词映射
      'grading': Prompts.generate_grading,
      'error-analysis': Prompts.generate_error_analysis,
      'ppt-page': Prompts.generate_ppt_page,
      'report-page': Prompts.generate_report_page,
    };
    return map[skillId] || Prompts.generate_lesson_plan;
  }

  global.WorkflowPrompts = {
    templates: Prompts,
    fill: fill,
    getGeneratePrompt: getGeneratePrompt,
  };
})(window);
